/**********************************************************************************************************************
 * \file TC375_GPT12_functions.c
 * \copyright Copyright (C) Harald Zweck 2025
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Harald Zweck.
 * If and as long as no such terms of use are agreed, use of this file is subject to following:
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*--------------------------------------------------Documentation----------------------------------------------------*/
/*********************************************************************************************************************/

/*
 * The code in this file shall provide the following functionalities:
 *
 * 1) initialize the GPT12 timer
 * 2) start the GPT12 timer
 * 3) stop the GPT12 timer
 * 4) (re)-load the GPT12 timer values
 *
 * Note: You can use the predefined port addresses in the include file IfxPort_reg.h
 */

/*
 * status: V01.0 2025-09-17
 */

/*********************************************************************************************************************/
/*-----------------------------------------------------Defines-------------------------------------------------------*/
/*********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/

/*
 * IfxPort_reg.h includes the definitions of the Infineon iLLDs for access to ports, peripherals, etc.
 */

#include <Level_Libraries/iLLD/TC37A/Tricore/Cpu/Std/Platform_Types.h>
#include <Level_04_HAL/HAL_Libraries/HAL_Return_Types.h>
#include <Level_04_HAL/TC375_SCU/TC375_SCU_WDT_functions.h>
#include <Level_Libraries/Infra/Sfr/TC37A/_Reg/IfxGpt12_reg.h>

/*********************************************************************************************************************/
/*-----------------------------------------------------Externals-----------------------------------------------------*/
/*********************************************************************************************************************/



/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/



/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*
 * function:    Func_GPT12_T6_init
 * returns:     HAL_Return_Type error report
 * parameters:  void
 * description: The function initializes the GPT12 module for operation
 */

HAL_Return_Type Func_GPT12_T6_init (void)
{
    HAL_Return_Type tmp_HAL = HAL_E_NOT_OK;

    Func_clear_Global_ENDINIT();

    /*
     * enable the GPT12 module and switch on the module clock
     * DISR = 0 -> clear disable request
     * EDIS = 1 -> disable sleep mode
     * other bits are reserved or read only
     */

    GPT120_CLC.B.DISR = 0x0;
    GPT120_CLC.B.EDIS = 0x1;

    Func_set_Global_ENDINIT();

    if(GPT120_CLC.B.DISS == 0x0)    // DISS == 0x0 -> GPT12 is successfully enabled
    {

        /*
         * the timer register T6 is configured for timer purposes
         *
         * field 02..00: T6I: 0x3, T6 internal divisor is set to 3
         * field 05..03: T6M: 0x0, T6 is set to timer mode
         * field 06: T6R: 0x0, T6 is stopped (it will be started separately)
         * field 07: T6UD: 0x1, T6 counts down
         * field 08: T6UDE: 0x0, count direction is controlled by T6UD
         * field 09: T6OE: 0x0, alternate output function disabled
         * field 10: T6OTL: 0x0, not used
         * field 12..11: BPS2: 0x2, divisor is - in combination with T6I - 128
         * field 14: T6CLR: 0x0, T6 is not cleared on a capture event
         * field 15: T6SR: 0x1, reload from CAPREL enabled
         */

        GPT120_T6CON.B.T6M   = 0x0;
        GPT120_T6CON.B.T6I   = 0x3;
        GPT120_T6CON.B.BPS2  = 0x2;
        GPT120_T6CON.B.T6UD  = 0x1;
        GPT120_T6CON.B.T6UDE = 0x0;
        GPT120_T6CON.B.T6CLR = 0x0;
        GPT120_T6CON.B.T6SR  = 0x1;
        GPT120_T6CON.B.T6R   = 0x0;
        GPT120_T6CON.B.T6OE  = 0x0;

        /*
         * GPT12 T6CON is not checked for correct setup
         */

        tmp_HAL = HAL_E_OK;
    }
    else
    {
        tmp_HAL = HAL_E_NOT_OK;
    }

    return tmp_HAL;
}


/*********************************************************************************************************************/
/*
 * function:    Func_GPT12_T6_start
 * returns:     HAL_Return_Type Error report
 * parameters:  void
 * description: The function starts the timer T6 of GPT12
 */

HAL_Return_Type Func_GPT12_T6_start (void)
{
    HAL_Return_Type tmp_HAL = HAL_E_NOT_OK;

    GPT120_T6CON.B.T6R   = 0x1;     // T6 started

    if(GPT120_T6CON.B.T6R == 0x1)
    {
        tmp_HAL = HAL_E_OK;
    }
    else
    {
        tmp_HAL = HAL_E_NOT_OK;
    }

    return tmp_HAL;
}


/*********************************************************************************************************************/
/*
 * function:    Func_GPT12_T6_stop
 * returns:     HAL_Return_Type Error report
 * parameters:  void
 * description: The function stops the timer T6 of GPT12
 */

HAL_Return_Type Func_GPT12_T6_stop (void)
{
    HAL_Return_Type tmp_HAL = HAL_E_NOT_OK;

    GPT120_T6CON.B.T6R   = 0x0;     // T6 stopped

    if(GPT120_T6CON.B.T6R == 0x0)
    {
        tmp_HAL = HAL_E_OK;
    }
    else
    {
        tmp_HAL = HAL_E_NOT_OK;
    }

    return tmp_HAL;
}


/*********************************************************************************************************************/
/*
 * function:    Func_GPT12_T6_set_value
 * returns:     HAL_Return_Type Error report
 * parameters:  unit16 timer_value: value to be loaded into T6
 * description: The function sets the counter value of timer T6 of GPT12
 */
HAL_Return_Type Func_GPT12_T6_set_value (uint16 timer_value)
{
    uint32 tmp;
    HAL_Return_Type tmp_HAL = HAL_E_NOT_OK;

    tmp = ((uint32)timer_value & 0x0000FFFF);   // T6 is a 16 bit timer
    GPT120_T6.U = tmp;

    if(GPT120_T6.U == tmp)
    {
        tmp_HAL = HAL_E_OK;
    }
    else
    {
        tmp_HAL = HAL_E_NOT_OK;
    }

    return tmp_HAL;
}


/*********************************************************************************************************************/
/*
 * function:    Func_GPT12_CAPREL_set_value
 * returns:     HAL_Return_Type Error report
 * parameters:  void
 * description: The function sets the counter value of timer CAPREL of GPT12
 */
HAL_Return_Type Func_GPT12_CAPREL_set_value (uint16 timer_value)
{
    uint32 tmp;
    HAL_Return_Type tmp_HAL = HAL_E_NOT_OK;

    tmp = ((uint32)timer_value & 0x0000FFFF);
    GPT120_CAPREL.U = tmp;

    if(GPT120_CAPREL.U == tmp)
    {
        tmp_HAL = HAL_E_OK;
    }
    else
    {
        tmp_HAL = HAL_E_NOT_OK;
    }


    return tmp_HAL;
}
